baseurl: "http://jgsqware.github.io"
languageCode: "en-us"
title: "jgsqware"
theme: herring-cove

params:
  ProfilePicture: "/images/profile.jpg"
  links:
    Home : "/"
  twitter: "https://twitter.com/jgsqware"
  github: "https://github.com/jgsqware"
